version: '3.3'

services:
  db:
    image: postgres:11

  redis:
    image: redis:latest

  api:
    build: api/.
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - gems:/gems
    ports:
      - "80:3000"
    restart: always
    environment:
      - RAILS_ENV=production

  sidekiq:
    build: api/.
    command: bundle exec sidekiq
    volumes:
      - gems:/gems
    environment:
      - RAILS_ENV=production
      - JOB_WORKER_URL=redis://redis:6379/

volumes:
  gems: {}
  program: {}
